name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-suite:
    needs: install-checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
        spark-version: [2.4.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        echo `python -V`
        pip install --upgrade pip setuptools wheel
        echo `python -V`
    - name: Do something else
      run: |
        echo `python -V`
